config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :projects
  get 'contacts' => 'contact#index'
  post 'contacts' => 'contact#create'

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,		:validate 	=> true
	attribute :email,		:validate 	=> /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,		:validate 	=> true
	attribute :subject,		:validate	=> true
	attribute :nickname,	:captcha	=> true

	def headers 
	 {
		:subject => %("#{subject}"),
		:to => "ospfolio@gmail.com",
		:from => %("#{name}" <#{email}>)
	 }
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	validate :picture_size

	private
	def picture_size
		if picture.size > 1.megabytes
			errors.add(:picture, "should be less than 1MB")
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index
  		@contact = Contact.new
  	end

  	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:success] = "Email was sent successfully."
		else
			flash.now[:error] = 'Cannot send message.'
			render :contact
		end
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  	@projects = Project.all.order("CREATED_AT DESC")
  	@contact = Contact.new
  end

  def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :contact
		end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("CREATED_AT DESC").paginate(:page => params[:page], :per_page => 9)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        flash.now[:success] = "Project was created."
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:projecttitle, :projectclient, :projectlink, :projectcategory, :projecthour, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def greet
	  now = Time.now
	  today = Date.today.to_time

	  morning = today.beginning_of_day
	  noon = today.noon
	  evening = today.change( hour: 17 )
	  tomorrow = today.tomorrow

	  if (morning..noon).cover? now
	    'Good Morning'
	  elsif (noon..evening).cover? now
	    'Good Afternoon'
	  elsif (evening..tomorrow).cover? now
	    'Good Evening'
	  end
   end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact/create.html.erb
<%= provide(:title, "Contact") %>
<!-- CONTACT SECTION START -->
    <section id="contact" class="section">
        <div class="container section-wrapper">
            <div class="section-content">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="section-title">Contact Me</h2>

                        <p class="section-subtitle">
                            Have a project you'd like to discuss?
                        </p>

                        <span class="divider center"></span>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                        <!-- CONTACT FORM START -->
                        <h1>Thank you for your message!</h1>
                        <p>I'll get back to you soon...</p>
                        <!-- //CONTACT FORM END -->

                    </div>
                    <!-- //.col-md-8 -->
                </div>
                <!-- //.row -->
            </div>
            <!-- //.section-content -->
        </div>
        <!-- //.container -->
    </section>
    <!-- //CONTACT SECTION END -->

app/views/contact/index.html.erb
<%= provide(:title, "Contact") %>
<!-- CONTACT SECTION START -->
    <section id="contact" class="section">
        <div class="container section-wrapper">
            <div class="section-content">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="section-title">Contact Me</h2>

                        <p class="section-subtitle">
                            Have a project you'd like to discuss?
                        </p>

                        <span class="divider center"></span>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                        <!-- CONTACT FORM START -->
                        <%= form_for(@contact, :html => { :name => 'contact-form', :id => 'contact-form', :class => 'contact-form validate element-line', :role => 'form' }) do |f| %>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="input-group input-group-lg">
                                            <%= f.text_field :name, id: "name", class: "form-control required", placeholder: "Name", autocomplete: "off", required: true %>
                                        </div>
                                        <!-- //.input-group -->
                                    </div>
                                    <!-- //.form-group -->
                                </div>
                                <!-- //.col-md-6 -->

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="input-group input-group-lg">
                                            <%= f.email_field :email, id: "email", class: "form-control required email", placeholder: "Email", autocomplete: "off", required: true %>
                                        </div>
                                        <!-- //.input-group -->
                                    </div>
                                    <!-- //.form-group -->
                                </div>
                                <!-- //.col-md-6 -->
                            </div>
                            <!-- //.row -->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="input-group input-group-lg">
                                            <%= f.text_field :subject, id: "subject", class: "form-control required", placeholder: "Subject", required: true %>
                                        </div>
                                        <!-- //.input-group -->
                                    </div>
                                    <!-- //.form-group -->
                                </div>
                                <!-- //.col-md-12 -->
                            </div>
                            <!-- //.row -->
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="input-group input-group-lg">
                                            <%= f.text_area :message, as: :text, id: "message", class: "form-control required", placeholder: "Message", required: true %>
                                        </div>
                                        <!-- //.input-group -->
                                    </div>
                                    <!-- //.form-group -->
                                </div>
                                <!-- //.col-md-12 -->
                            </div>
                            <!-- //.row -->

                            <div class="hidden">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="input-group input-group-lg">
                                            <%= f.text_field :nickname, hint: 'leave this field blank' %>
                                        </div>
                                        <!-- //.input-group -->
                                    </div>
                                    <!-- //.form-group -->
                                </div>
                                <!-- //.col-md-6 -->
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                    <%= button_tag(type: 'submit', id: 'submit') do %>
                                        Say Hello
                                    <% end %>
                                    </div>
                                    <!-- //.form-group -->
                                </div>
                                <!-- //.col-md-12 -->
                            </div>
                            <!-- //.row -->
                        <% end %>
                        <!-- //CONTACT FORM END -->

                    </div>
                    <!-- //.col-md-8 -->
                </div>
                <!-- //.row -->
            </div>
            <!-- //.section-content -->
        </div>
        <!-- //.container -->
    </section>
    <!-- //CONTACT SECTION END -->

app/views/home/_portfolio.html.erb
<!-- PORTFOLIO SECTION START -->
    <section id="portfolio" class="section">
        <div class="container-fluid section-wrapper">
            <div class="section-content">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="section-title">My Latest Work</h2>

                        <p class="section-subtitle">I'm looking to expand my portfolio while I'm on top and while I'm young.</p>

                        <span class="divider center"></span>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <div class="row">
                    <div class="col-md-12">
                        <ul class="filterable-portfolio-nav list-inline text-center">
                            <li class="active">
                                <a href="#" data-filter="*" class="btn btn-sm btn-custom disabled">All</a>
                            </li>

                            <li>
                                <a href="#" data-filter=".design" class="btn btn-sm btn-custom">Design</a>
                            </li>
                            
                            <li>
                                <a href="#" data-filter=".web" class="btn btn-sm btn-custom">Web App</a>
                            </li>
                            
                            <li>
                                <a href="#" data-filter=".mobile" class="btn btn-sm btn-custom">Mobile App</a>
                            </li>
                        </ul>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <!-- PORTFOLIO START -->
                <div class="portfolio">
                    <div class="row filterable-portfolio">
                    <% @projects.each do |project| %>
                    <div class="item <%= project.projectcategory %> col-sm-6 col-md-3">
                            <div class="project-wrapper">
                                <div class="project-link">
                                    <a href="<%= project.picture %>" class="zoom" title="<%= project.projecttitle %>">
                                        <i class="ion-arrow-expand"></i>
                                    </a>

                                    <%= link_to raw("<i class='ion-link'></i>"), "http://#{project.projectlink}", :target => "_blank", class: "external-link" %>
                                
                                </div>
                                <!-- //.project-link -->

                                <div class="project-title">
                                    <h4><%= project.projecttitle %></h4>

                                </div>
                                <!-- //.project-title -->

                                <%= image_tag(project.picture.url, size: "768x590", class: "img-responsive") if project.picture? %>
                            </div>
                            <!-- //.project-wrapper -->
                        </div>
                        <!-- //.item -->
                    <% end %>
                    </div>
                    <!-- //.row -->
                </div>
                <!-- PORTFOLIO END -->
                <% if !@projects.any? %>
                <div class="row">
                    <div class="col-md-12">
                        <div class="launch text-center" style="margin: 50px 0;">
                            <%= link_to "Show All", projects_path, class: "btn btn-lg btn-custom" %>
                        </div>
                        <!-- //.launch -->
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <% end %>
                <!-- //.row -->
            </div>
            <!-- //.section-content -->
        </div>
        <!-- //.container-fluid -->
    </section>
    <!-- //PORTFOLIO SECTION END -->

app/views/home/index.html.erb
<%= provide(:title, "Portfolio") %>
<%= render '/home/profile' %>
<%= render '/home/portfolio' %>
<%= render '/home/workflow' %>
<%= render '/home/resume' %>
<%= render '/home/skill' %>
<%= render '/home/knowledge' %>
<%= render :template => '/home/contact' %>

app/views/layouts/_header.html.erb
<!-- HERO START -->
<header id="home" class="hero parallax-yes">
    <div id="parallax-1" class="parallax">
        <div class="bcg skrollable skrollable-between" data-anchor-target="#parallax-1" data-center="background-position: 50% 0px;" data-top-bottom="background-position: 50% -100px;" data-bottom-top="background-position: 50% 100px;">
            <div class="hero-body">
                <div class="hero-text text-center">
                    <h1 class="small">
                    I'm OSP <span class="blinker"></span>
                    </h1>
                    <h1 class="small"><span id="js-rotating">Web Developer | UI/UX Designer | Mobile App Developer</span></h1>
                    <p>22 years young, freelancer.</p>
                    <div class="page-scroll">
                        <a href="#profile" class="btn btn-lg btn-custom">
                            <%= greet %>
                        </a>
                    </div>
                    <!-- //.page-scroll -->
                </div>
                <!-- //.hero-text -->
            </div>
            <!-- //.hero-body -->
        </div>
        <!-- //.bcg -->
    </div>
    <!-- //.parallax -->
</header>
<!-- //HERO END -->

app/views/layouts/_map.html.erb
<!-- MAP START -->
    <div id="map">
        <div class="address">
            <h4>123 Water Seven, Grand Line</h4>
        </div>
        <!-- //.address -->
        
        <div id="cd-google-map">
            <div id="google-container"></div>
        </div>
        <!-- //.cd-google-map -->
    </div>
    <!-- //MAP END -->

app/views/layouts/_nav.html.erb
<!-- NAVIGATION START -->
    <nav id="navigation" class="navbar navbar-fixed-top center-menu" role="navigation">
        <div class="container navbar-container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".berg-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a class="navbar-brand visible-xs" href="#page-top">OSP</a>
            </div>
            <!-- //.navbar-header -->
            
            <div class="navbar-collapse collapse berg-collapse">
                <ul class="nav navbar-nav">
                    <% if user_signed_in? && current_user.admin? %> 
                        <li class="page-scroll">
                            <%= link_to('Home', root_path, :method => :get) %>
                        </li>
                        
                        <li class="page-scroll">
                            <%= link_to('All Projects', projects_path, :method => :get) %>
                        </li>

                        <li class="page-scroll">
                            <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
                    <% else %>
                        <li class="page-scroll">
                            <%= link_to('Home', root_path, :method => :get) %>
                        </li>
                        
                        <li class="page-scroll">
                            <%= link_to('Portfolio', projects_path, :method => :get) %>
                        </li>
                        
                        <li class="page-scroll">
                            <%= link_to('Contact', contacts_path, :method => :get) %>
                        </li>
                    <% end %> 
                </ul>
            </div>
            <!-- //.navbar-collapse -->
        </div>
        <!-- //.navbar-container -->
    </nav>
    <!-- //NAVIGATION END -->

app/views/layouts/_navhome.html.erb
<!-- NAVIGATION START -->
    <nav id="navigation" class="navbar navbar-fixed-top center-menu" role="navigation">
        <div class="container navbar-container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".berg-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a class="navbar-brand visible-xs" href="#page-top">OSP</a>
            </div>
            <!-- //.navbar-header -->
            
            <div class="navbar-collapse collapse berg-collapse">
                <ul class="nav navbar-nav">
                    <% if user_signed_in? && current_user.admin? %>
                        <li class="page-scroll">
                        <%= link_to('Home', root_path, :method => :get) %>
                        </li>
                        
                        <li class="page-scroll">
                            <%= link_to('All Projects', projects_path, :method => :get) %>
                        </li>

                        <li class="page-scroll">
                            <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
                    <% else %>
                        <li class="page-scroll">
                            <a href="#home">Home</a>
                        </li>
                        
                        <li class="page-scroll">
                            <a href="#portfolio">Portfolio</a>
                        </li>
                        
                        <li class="page-scroll">
                            <a href="#contact">Contact</a>
                        </li>
                    <% end %> 
                </ul>
            </div>
            <!-- //.navbar-collapse -->
        </div>
        <!-- //.navbar-container -->
    </nav>
    <!-- //NAVIGATION END -->

app/views/projects/edit.html.erb
<!-- CONTACT SECTION START -->
    <section id="contact" class="section">
        <div class="container section-wrapper">
            <div class="section-content">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="section-title">Editing Project</h2>

                        <p class="section-subtitle">
                            Anything, you want to change? Do it here :D
                        </p>
						<%= link_to 'Show', @project %> |
						<%= link_to 'Back', projects_path %>
                        <span class="divider center"></span>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                        <!-- CONTACT FORM START -->
                        <%= render 'form' %>
                        <!-- //CONTACT FORM END -->

                    </div>
                    <!-- //.col-md-8 -->
                </div>
                <!-- //.row -->
                
            </div>
            <!-- //.section-content -->
        </div>
        <!-- //.container -->
    </section>
    <!-- //CONTACT SECTION END -->

app/views/projects/index.html.erb
<%= provide(:title, "Projects") %>
<!-- PORTFOLIO SECTION START -->
    <section id="portfolio" class="section">
        <div class="container-fluid section-wrapper">
            <div class="section-content">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="section-title">All Projects</h2>

                        <p class="section-subtitle">this is where you can see all of my projects.</p>
                        <% if user_signed_in? && current_user.admin? %>
                        <%= link_to 'New Project', new_project_path %>
                        <% end %>
                        <span class="divider center"></span>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <div class="row">
                    <div class="col-md-12">
                        <ul class="filterable-portfolio-nav list-inline text-center">
                            <li class="active">
                                <a href="#" data-filter="*" class="btn btn-sm btn-custom disabled">All</a>
                            </li>

                            <li>
                                <a href="#" data-filter=".design" class="btn btn-sm btn-custom">Design</a>
                            </li>
                            
                            <li>
                                <a href="#" data-filter=".web" class="btn btn-sm btn-custom">Web App</a>
                            </li>
                            
                            <li>
                                <a href="#" data-filter=".mobile" class="btn btn-sm btn-custom">Mobile App</a>
                            </li>
                        </ul>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <!-- PORTFOLIO START -->
                <div class="portfolio">
                    <div class="row filterable-portfolio">
                    <% @projects.each do |project| %>
                    <div class="item <%= project.projectcategory %> col-sm-6 col-md-3">
                            <div class="project-wrapper">
                                <div class="project-link">
                                    <% if user_signed_in? && current_user.admin? %>
                                        <a href="<%= project.picture %>" class="zoom" title="Buzz Lightyear">
                                        <i class="icon-Full-Screen"></i>
                                    </a>
                                    <%= link_to raw("<i class='icon-Link'></i>"), "http://#{project.projectlink}", :target => "_blank", class: "external-link" %>
                                    <% end %>
                                </div>
                                <!-- //.project-link -->
                                <% if user_signed_in? && current_user.admin? %>
                                <div class="project-title">
                                    <h4><%= project.projecttitle %></h4>

                                </div>
                                <% end %>
                                <!-- //.project-title -->

                                <%= image_tag(project.picture.url, size: "768x590", class: "img-responsive") if project.picture? %>
                            </div>
                            <div class="project-title" style="text-align: center">
                                <% if user_signed_in? && current_user.admin? %>
                                    <h4 style="display: inline-block; margin-right: 10px;"><%= link_to 'Edit', edit_project_path(project) %></h4>
                                    <h4 style="display: inline-block;"><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></h4>
                                <% end %>
                            </div>
                            <!-- //.project-wrapper -->
                        </div>
                        <!-- //.item -->
                    <% end %>
                    </div>
                    <!-- //.row -->
                </div>
                <!-- PORTFOLIO END -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="launch text-center" style="margin-top: 80px;">
                            <%= will_paginate @projects %>
                        </div>
                        <!-- //.launch -->
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
            </div>
            <!-- //.section-content -->
        </div>
        <!-- //.container-fluid -->
    </section>
    <!-- //PORTFOLIO SECTION END -->
     <section id="resume" class="section">
         <div class="container section-wrapper">
            <div class="section-content">
                <div class="row"></div>
            </div>
        </div>
     </section>

app/views/projects/new.html.erb
<!-- CONTACT SECTION START -->
    <section id="contact" class="section">
        <div class="container section-wrapper">
            <div class="section-content">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2 class="section-title">New Project</h2>

                        <p class="section-subtitle">
                            Here is where you can show the world with your awesome project :)
                        </p>
                        <%= link_to 'Back', projects_path %>
                        <span class="divider center"></span>
                    </div>
                    <!-- //.col-md-12 -->
                </div>
                <!-- //.row -->
                
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                        <!-- CONTACT FORM START -->
                        <%= render 'form' %>
                        <!-- //CONTACT FORM END -->

                    </div>
                    <!-- //.col-md-8 -->
                </div>
                <!-- //.row -->

            </div>
            <!-- //.section-content -->
        </div>
        <!-- //.container -->
    </section>
    <!-- //CONTACT SECTION END -->

app/views/projects/show.html.erb
<%= notice %>
<div class="row">
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag(@project.picture.url, size: "200x200", class: "gravatar") if @project.picture? %>
      <div class="caption">
        <h3><%= @project.projecttitle %></h3>
        <p><%= @project.projectclient %></p>
        <p><%= @project.projectlink %></p>
        <p><%= @project.projectcategory %></p>
        <p><%= @project.projecthour %></p>
        <p>
          <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary", role: "button" %>
          <%= link_to 'Back', projects_path, class: "btn btn-default", role: "button" %> 
        </p>
      </div>
    </div>
  </div>
</div>